version: "3.8"

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 5s
      timeout: 5s
      retries: 3

  player:
    container_name: player
    build: ./player
    ports:
     - "8000:8000"

  hrm:
    container_name: hrm
    build: ./hrm
    ports:
      - "8004:8004"
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      #- POSTGRES_URL=postgres://postgres:postgres@postgres:5432/postgres
    depends_on:
      rabbitmq:
        condition: service_healthy
      player:
        condition: service_started

  workout:
    container_name: workout
    build: ./workout
    ports:
      - "8001:8001"
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      rabbitmq:
        condition: service_healthy
      hrm:
        condition: service_started
      player:
        condition: service_started
